name: E1 Runner

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-e1-player:
    name: E1 Key Extractor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 10
            run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
#          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        working-directory: ./e1-player

      - name: Run extractor
        run: npx ts-node ./src/index.ts
        working-directory: ./e1-player/

      - name: Commit and push keys if changed
        working-directory: ./e1-player/src/data
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add keys.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "[auto] Update keys"
          git push